---

# plugins: [flowtype]

env:
  node: true
  jest: true
  jasmine: true

parser: babel-eslint

parserOptions:
  ecmaVersion: 2017
  sourceType: module

extends:
  - 'airbnb-base'
  - plugin:import/errors
  - plugin:import/warnings

rules:
  consistent-return: 0
  no-underscore-dangle: 0
  no-console: 0
  import/extensions:
      - off
      - never